# disable annoying metric cops
Metrics/LineLength:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Style/ConditionalAssignment:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false  